version: "3.7"

services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
